# This is a basic workflow to help you get started with Actions
name: Docker tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-docker-tests:
    name: docker tests
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # run the tests
      - name: n005w4_0_1-2-3-3
        uses: ./ # Uses an action in the root directory
        with:
          ns-args: -i n005w4_0_1-2-3-3 -g 1550

      - name: n030w4_1_6-2-9-1
        uses: ./ # Uses an action in the root directory
        with:
          ns-args: -i n030w4_1_6-2-9-1 -g 1800-1950 -t 120

      - name: n030w4_1_6-7-5-3
        uses: ./ # Uses an action in the root directory
        with:
          ns-args: -i n030w4_1_6-7-5-3 -g 1950-2150 -t 120

      - name: n035w4_1_1-7-1-8
        uses: ./ # Uses an action in the root directory
        with:
          ns-args: -i n035w4_1_1-7-1-8 -g 1350-1500 -t 120

      - name: n030w4_1_6-2-9-1 Dynamic
        uses: ./ # Uses an action in the root directory
        with:
          ns-args: -d -i n030w4_1_6-2-9-1 -s 68-54-78-98 -g 1800-2000

      - name: n030w4_1_6-7-5-3 Dynamic
        uses: ./ # Uses an action in the root directory
        with:
          ns-args: -d -i n030w4_1_6-7-5-3 -s 50-35-70-80 -g 2000-2150

      - name: n030w4_1_6-7-5-3 Dynamic
        uses: ./ # Uses an action in the root directory
        with:
          ns-args: -d -i n035w4_1_1-7-1-8 -s 85-76-52-66 -g 1450-1600
